project:
  type: website
  output-dir: docs
  
website:
  title: "Introduction to Multivariate Statistics"
  sidebar:
    search: true
    style: "docked"
    contents: 
      - text: "Preface"
        href: "index.qmd"
      - section: "Module 1: Introduction"
        href: ch1/01-intro.qmd
      - section: "Module 2: Graphs and Data Visualization"
        href: ch2/02-graphs.qmd
      - section: "Module 3: Multivariate Normal Distribution"
        href: ch3/03-MVN.qmd
      # - href: ch4/04-Inference_for_Means.qmd
      # - href: ch5/05-Inference_for_Means_II.qmd 
      # - href: ch6/06-PCA.qmd
      # - href: ch7/07-FactorAnalysis.qmd
      # - href: summary.qmd
      # - href: references.qmd

bibliography: references.bib

format:
  html:
    html-math-method: katex
    include-in-header:
      - text: |
          <script>
            window.MathJax = {
              loader: {
                load: ['[tex]/amsmath', '[tex]/amssymb', '[tex]/amsfonts'],
                '[tex]/color']
              },
              tex: {
                packages: { '[+]': ['amsmath', 'amssymb', 'amsfonts', 'color'] }
              }
            };
          </script>
    css: custom.css
    toc: true
    toc-expand: 1
    toc_depth: 3
    sidebar:
      style: floating 
      collapse-level: 1
    number-sections: true
    code-fold: true
    callout-appearance: default
    theme: cosmo


