project:
  type: book
  output-dir: docs

  
book:
  title: "Introduction to Multivariate Data Analysis"
  author: "Pulong Ma"
  date: last-modified
  date-format: MMM, D, YYYY 
  chapters:
    - index.qmd
    - ch1/01-intro.qmd
    - ch2/02-graphs.qmd
    - ch3/03-MVN.qmd
    - ch4/04-Inference_for_Means.qmd
    - ch5/05-Inference_for_Means_II.qmd 
    # - ch6/06-PCA.qmd
    # - ch7/07-FactorAnalysis.qmd
    # - summary.qmd
    # - references.qmd
    
bibliography: references.bib

format:
  html:
    html-math-method: katex
    include-in-header:
      - text: |
          <script>
            window.MathJax = {
              loader: {
                load: ['[tex]/amsmath', '[tex]/amssymb', '[tex]/amsfonts'],
                '[tex]/color']
              },
              tex: {
                packages: { '[+]': ['amsmath', 'amssymb', 'amsfonts', 'color'] }
              }
            };
          </script>
    css: custom.css
    toc: true
    toc-expand: 1
    toc_depth: 3
    sidebar:
      style: floating 
      collapse-level: 1
    number-sections: true
    code-fold: true
    callout-appearance: default
    theme: cosmo

